const cabins = {
        'Dr. S. Kannan': {'Link': 'G-01'},
        'Dr. Vinod Bhatt': {'Link': 'G-02'},
        'Dr. G. Vishnuvarthanan': {'Link': 'G-03'},
        'Dr. Manisha Jain': {'Link': 'G-04'},
        'Dr. Jasmine Selvakimari': {'Link': 'G-05'},
        'Dr. Manoj Acharya': {'Link': 'G-06'},
        'Dr. Paras Jain': {'Link': 'G-07'},
        'Dr. Lakshmi D.': {'Link': 'G-08'},
        'Dr. Pushpinder Singh Patheja': {'Link': 'G-09'},
        'Dr. Dev Brat Gupta': {'Link': 'G-10'},
        'Dr. R. Senthil Kumar': {'Link': 'G-11'},
        'Dr. Zaheer Kareem Ansari': {'Link': 'G-12'},
        'Dr. Nikhil Pateria': {'Link': 'G-13'},
        'Dr. G.R. Hemalakshmi': {'Link': 'G-14'},
        'Dr. Venkat Padhy': {'Link': 'G-15'},
        'Vijay Kumar Trivedi': {'Link': 'G-17'},
        'Dr. Abha Sharma': {'Link': 'G-18'},
        'Dr. Dileep Kumar': {'Link': 'G-19'},
        'D. Harish Babu': {'Link': 'G-20'},
        'J.P. Shritharanyaa': {'Link': 'G-21'},
        'Dr. Buvaneswari': {'Link': 'G-22'},
        'Dr. Rajit Nair': {'Link': 'G-25'},
        'Dr. Trapti Sharma': {'Link': 'G-26'},
        'Dr. Abhay Vidyarthi': {'Link': 'G-27'},
        'Dr. M Suresh': {'Link': 'G-28'},
        'Dr. M Manimaran': {'Link': 'G-29'},
        'Dr. Sirajudeen A': {'Link': 'G-30'},
        'Dr. Krishna Chouhan': {'Link': 'G-31'},
        'Dr. S Devaraju': {'Link': 'G-32'},
        'Dr. Manisha Singh': {'Link': 'G-33'},
        'Dr. Praveen Lalwani': {'Link': 'A-101'},
        'Dr. Sheetal Sharma': {'Link': 'A-102'},
        'Dr. Baseera A': {'Link': 'A-103'},
        'Dr. M K Jayanthi Kannan': {'Link': 'A-104'},
        'Dr. Adnan Abbasi': {'Link': 'A-107'},
        'Dr. Arun Kumar K.': {'Link': 'A-108'},
        'Dr. Hemant Kumar Nashine': {'Link': 'A-109'},
        'Dr. Pavan Kumar': {'Link': 'A-110'},
        'Dr. Rupesh Kumari': {'Link': 'A-111'},
        'Dr. Chandrabhan Seniya': {'Link': 'A-112'},
        'Dr. Faisal Rasheed Lone': {'Link': 'A-113'},
        'Dr. Sajjad Ahmed': {'Link': 'A-114'},
        'Sripriyan': {'Link': 'A-115'},
        'Mr. Abhishek Kumar': {'Link': 'A-116'},
        'Azra Nazir': {'Link': 'A-117'},
        'Ms Manorama Chouhan': {'Link': 'A-118'},
        'Arindam Sadhukhan': {'Link': 'A-119'},
        'Ajay Sharma': {'Link': 'A-120'},
        'Bhupendra Panchal': {'Link': 'A-121'},
        'Pranshu Pranjal': {'Link': 'A-122'},
        'Dr. Jayanthi J': {'Link': '1st floor Ext. Cabin'},
        'Mamta Agarwal': {'Link': 'A-201'},
        'Dr. Pon Harshavardhanan': {'Link': 'A-202'},
        'Navneet Kumar Verma': {'Link': 'A-203'},
        'Shweta Mukherjee': {'Link': 'A-204'},
        'Dr. Subash Chandra Bose': {'Link': 'A-205'},
        'Dr. Sasmita Padhy': {'Link': 'A-206'},
        'Dr. Sandip Mal': {'Link': 'A-207'},
        'Dr. Preetam Suman': {'Link': 'A-208'},
        'Dr. Jyothi Chouhan': {'Link': 'A-209'},
        'Balaguru S': {'Link': 'A-210'},
        'Dr. Vinesh Kumar': {'Link': 'A-211'},
        'Dr. M. Maragatharajan': {'Link': 'A-212'},
        'Dr. Pijush Kanti Mondal': {'Link': 'A-214'},
        'Dr. Poulami Ghosh': {'Link': 'A-215'},
        'Harish Chandra': {'Link': 'A-216'},
        'Dr. Dheresh Soni': {'Link': 'A-217'},
        'Dr. Gopal S Tandel': {'Link': 'A-218'},
        'Dr. Vivek Shama': {'Link': 'A-219'},
        'Ujjwal Kumar Mishra': {'Link': 'A-220'},
        'Mr. Jay Prakash Maurya': {'Link': 'A-221'},
        'Ar. Vipendra Singh': {'Link': 'A-222'},
        'Dr. Abdul Rehman': {'Link': 'A-223'},
        'Dr. S. Aanjankumar': {'Link': 'A-224'},
        'Karthik Rao M C': {'Link': 'A-225'},
        'Dr. Vijay Kumar Patidar': {'Link': 'A-226'},
        'Dr. Rajdeep Ghosh': {'Link': 'A-227'},
        'Dr. Umakanta Meher': {'Link': 'A-228'},
        'Abhishek Shrivastava': {'Link': 'A-229'},
        'Vijay Kumar Patel': {'Link': 'A-232'},
        'Suchismita Patra': {'Link': 'A-233'},
        'Rahul Kumar Chaturvedi': {'Link': 'A-234'},
        'Dr. Shahana Gajala Qureshi': {'Link': 'A-235'},
        'Swati Chauhan': {'Link': 'A-236'},
        'Anil Kumar': {'Link': 'A-237'},
        'Dr. Juhi Yasmeen': {'Link': 'A-238'},
        'Dr. Vivek Parashar': {'Link': 'A-239'},
        'Dr. Kannaiya Raja N': {'Link': 'A-240'},
        'Dr. A Balaji': {'Link': 'A-241'},
        'Dr. Siddharth S Chouhan': { 'Link': 'A-242' },
        'Dr. Sivasankaran': { 'Link': 'A-243' },
        'Dr. Ankur Beohar': { 'Link': 'A-244' },
        'Dr. Siddartha Maiti': { 'Link': 'A-245' },
        'Dr. Soumitra Keshari Nayak': { 'Link': 'A-246' },
        'Dr. Swagat Samantray': { 'Link': 'A-247' },
        'Dr. Rajeev': { 'Link': 'A-248' },
        'Dr. Sarvanan D': { 'Link': 'A-249' },
        'Dr. GK': { 'Link': 'A-250' },
        'Dr. Gunjan Ansari': { 'Link': '2nd floor Ext. Cabin' },
        'Ajay Kumar Bhurjee': { 'Link': 'A-301' },
        'Akshara Makrariya': { 'Link': 'A-302' },
        'Kumar Pandey': { 'Link': 'A-303' },
        'Dr. Bhakti Parashar': { 'Link': 'A-304' },
        'T Venkateswarao': { 'Link': 'A-305' },
        'Rajneesh Kumar Patel': { 'Link': 'A-306' },
        'Shivmanjree Gopaliya': { 'Link': 'A-307' },
        'Dr. Ramu Pashupathi Suganeshwar': { 'Link': 'A-308' },
        'Dr. Virendra Singh Kushwah': { 'Link': 'A-309' },
        'Pallabi Sarkar': { 'Link': 'A-310' },
        'Suchetana Sadhukhan': { 'Link': 'A-311' },
        'Dr. Ganeshan R': { 'Link': 'A-312' },
        'Avirup Das': { 'Link': 'A-313' },
        'Dr. Sonal Gupta': { 'Link': 'A-314' },
        'Anita Yadav': { 'Link': 'A-315' },
        'Dr. OP Pahari': { 'Link': 'A-316' },
        'Dr. Pradeep Kumar Mishra': { 'Link': 'A-317' },
        'Dr. Bhumika Choksi': { 'Link': 'A-318' },
        'Dr. Anjali Mathur': { 'Link': 'A-319' },
        'Rohit Sharma': { 'Link': 'A-320' },
        'VVPRVB Suresh Dara': { 'Link': 'A-321' },
        'Dr. Anvesh Nella': { 'Link': 'A-322' },
        'Dr. Periyanagi': { 'Link': 'A-323' },
        'Dr. Vikas Panthi': { 'Link': 'A-324' },
        'Dr. Pradeep Kashyap': { 'Link': 'A-325' },
        'Dr. Ashok K Patel': { 'Link': 'A-326' },
        'Ms. Ravina Toppo': { 'Link': '3rd floor Ext. Cabin' },
        'Dr. Hariharan R': { 'Link': 'B-301' },
        'Nilam Venkatakoteswararao': { 'Link': 'B-302' },
        'Sheerin Kayenat': { 'Link': 'B-303' },
        'Sumit Mittal': { 'Link': 'B-304' },
        'Dr. Monika Sankat': { 'Link': 'B-305' },
        'Harshlata Vishwakarma': { 'Link': 'B-306' },
        'Narottam Das Patel': { 'Link': 'B-307' },
        'Dr. Nilamadhab Mishra': { 'Link': 'B-308' },
        'Dr. C. P. Koushik': { 'Link': 'B-309' },
        'Chandrama Swain': { 'Link': 'B-310' },
        'Dr. H. Azath': { 'Link': 'B-311' },
        'Xavier': { 'Link': 'B-312' },
        'Dr. A V R Mayuri': {'Link': 'B-313'},
        'Dr. Ajeet Singh': { 'Link': 'B-315' },
        'Benevatho Jaison A': { 'Link': 'A-401' },
        'Dr. Komarasamy G': { 'Link': 'A-402' },
        'Dr. K. Murugeswari': { 'Link': 'A-403' },
        'Dr. Subhash Chandra Patel': { 'Link': 'A-404' },
        'Saravanan J': { 'Link': 'A-405' },
        'Abdul Rashid': { 'Link': 'A-406' },
        'Dr. Jothiaruna': { 'Link': 'A-407' },
        'Dr. Abhinav Kumar': { 'Link': 'A-408' },
        'Shiv Shankar Prasad': { 'Link': 'A-409' },
        'Ajay Kumar Phulre': { 'Link': 'A-410' },
        'M. Nirmala': { 'Link': 'A-411' },
        'Pushpdant Jain': { 'Link': 'A-412' },
        'Jitendra Pratap Singh Mathur': { 'Link': 'A-413' },
        'Mrs. Kumkum Dueby': { 'Link': 'A-414' },
        'Dr. Ganeshan G.': { 'Link': 'A-415' },
        'Dr. Enagandula Prasad': { 'Link': 'A-416' },
        'Dr. Pankaj Kumar': { 'Link': 'A-417' },
        'Dr. Md. Zeeshan': { 'Link': 'A-418' },
        'Dr. Mayank Sharma': { 'Link': 'A-419' },
        'Dr. Amrita Parashar': { 'Link': 'A-420' },
        'Nagarajan I': { 'Link': 'A-421' },
        'Ms. Kalyani Wankehde': { 'Link': 'A-422' },
        'Dr. Saurabh Mishra': { 'Link': 'A-423' },
        'Dr. Ramraj Dangi': { 'Link': 'A-424' },
        'Dr. Sonjoy Pan': { 'Link': 'A-425' },
        'Dr. Sumit Som': { 'Link': 'A-426' },
        'Dr. Santosh Sahu': { 'Link': '4th floor Ext. Cabin' },
        'Saurabh Bhargava': { 'Link': 'B-401' },
        'Dr. Ranjitha Kumar': { 'Link': 'B-402' },
        'Dr. Priscilla Dinkar Morya': { 'Link': 'B-403' },
        'Devraj Vishnu': { 'Link': 'B-404' },
        'Dr. Ankur Jain': { 'Link': 'B-405' },
        'Mr. Ashfaq Ahmed': { 'Link': 'B-406' },
        'Dr. Anand Motwani': { 'Link': 'B-407' },
        'Dr. Thamim': { 'Link': 'B-408' },
        'Dr. Jagriti Gupta': { 'Link': 'B-409' },
        'Badla Pawan Babu': { 'Link': 'B-410' },
        'Dr. Ankush Tharkar': { 'Link': 'B-411' },
        'E. Nirmala': { 'Link': 'B-412' },
        'Md. Tauseef Qamar': { 'Link': 'B-413' },
        'Dr. Arup Torai': { 'Link': 'B-414' },
        'Dr. Pavithra Rathinavel': { 'Link': 'B-415' },
        'Dr. Nilesh Kunhare': { 'Link': 'C-401' },
        'Ms. Deeksha Singh': { 'Link': 'C-402' },
        'Adarsh Patel': { 'Link': 'C-403' },
        'Dr. Gaurav Soni': { 'Link': 'C-404' },
        'Dr. Saravanan S': { 'Link': 'A-501' },
        'Ankit Pal': { 'Link': 'A-502' },
        'Chour Singh Rajput': { 'Link': 'A-503' },
        'Dr. Raghavendra Mishra': { 'Link': 'A-504' },
        'Arindam Ghosh': { 'Link': 'A-505' },
        'B. Mahendran': { 'Link': 'A-506' },
        'Dipankar Sutradhar': { 'Link': 'A-507' },
        'Humaira Fatima': { 'Link': 'A-509' },
        'Dr. Anju': { 'Link': 'A-510' },
        'Dr. Manoj Kumar': { 'Link': 'A-511' },
        'Santosh Kumar Bhal': { 'Link': 'A-512' },
        'Jitendra Parmar': { 'Link': 'A-513' },
        'Dr. Ravi Verma': { 'Link': 'A-514' },
        'Dr. Juhi Kesarwany': { 'Link': 'A-515' },
        'Mr. Santanu Mandal': { 'Link': 'A-516' },
        'Dr. Sanjib Nayak': { 'Link': 'A-517' },
        'Dr. Shweta Singh': { 'Link': 'A-518' },
        'Dr. P Monica': { 'Link': 'A-519' },
        'Dr. Saurabh Kumar Maurya': { 'Link': 'A-520' },
        'P. Vayunandanakishore': { 'Link': 'A-521' },
        'Hemanta Kalita': { 'Link': 'A-522' },
        'Kiran Kumar Behera': { 'Link': 'A-523' },
        'Dr. Dipanjana Hazra': { 'Link': 'A-524' },
        'Dr. Arya Priyadarshini': { 'Link': 'A-525' },
        'Khatavkar Vaibhav Kashinath': { 'Link': 'A-526' },
        'Dr. Rahul Shrivastava': { 'Link': '5th floor Ext. Cabin' },
        'DR. RUDRA KALYAN NAYAK': { 'Link': 'B-501' },
        'Dr. Dip Mukherjee': { 'Link': 'B-502' },
        'N. Vignesh': { 'Link': 'B-503' },
        'Jyoti Badge': { 'Link': 'B-504' },
        'Dr. Feroz Babu': { 'Link': 'B-505' },
        'Ms. Pooja': { 'Link': 'B-506' },
        'Ms. Geeta Singh': { 'Link': 'B-507' },
        'Dr. S. K. Das': { 'Link': 'B-508' },
        'Usama Khan': { 'Link': 'B-509' },
        'Mr. Vipin Jain': { 'Link': 'B-510' },
        'Irfan Alam': { 'Link': 'B-511' },
        'Dr. Suneet Joshi': { 'Link': 'B-512' },
        'Dr. Shafiul Alom Ahmed': { 'Link': 'B-513' },
        'Abhishek Raj': { 'Link': 'B-514' },
        'Rajdeep Singh Payal': { 'Link': 'B-515' },
        'Dr. Ram Kumar': { 'Link': 'C-501' },
        'Amit Kumar Singh': { 'Link': 'C-502' },
        'A. Manickam': { 'Link': 'C-503' },
        'Dr. Sultan Alam': { 'Link': 'C-504' },
        'Vijendra Singh Bramhe': { 'Link': 'C-505' },
        'Saurav Prasad': { 'Link': 'C-506' },
        'Sukumar': { 'Link': 'C-507' },
        'Ms. Nancy Kumari': { 'Link': 'C-508' },
        'Dr. Hemraj S.L.': { 'Link': 'C-509' },
        'Dr. Vinod Kumar Jatav': {'Link': 'C-510'},
        'Dr. Shweta Saxena': {'Link': 'C-511'},
        'Soma Saha': {'Link': 'C-512'},
        'Santosh Kumar Tripathy': {'Link': 'C-513'},
        'Mr. Sanat Jain': {'Link': 'C-514'},
        'Dr. Shahab Saquib Sohail': {'Link': 'C-515'},
        'Dr. G. PRABU KANNA': {'Link': 'C-516'},
        'D. SARAVANAN': {'Link': 'C-517'},
        'Dr. Rizwan ur Rahman': {'Link': 'C-518'},
        'Dr. Vikas Panthi': {'Link': 'C-519'},
        'Mohd Rafi Lone': {'Link': 'C-520'},
        'Dr. NITIN KUMAR MISHRA': {'Link': 'C-521'},
        'Dr. Ashish Kesarwany': {'Link': 'C-523'},
        'Deep Chandra Upadhyay': {'Link': 'C-524'},
        'Priyanka Roy': {'Link': 'C-525'},
        'Dr. Ashish Mohan Yadav': {'Link': 'C-527'},
        'Mr. Vishal Singh Bhati': {'Link': 'C-528'},
        'Dr. S. Periyanayagi': {'Link': 'C-529'},
        'Dr. Abha Trivedi': {'Link': 'C-530'},
        'Ashok Kumar Baral': {'Link': 'C-531'},
        'Dr. KR. SIVABALAN': {'Link': 'C-532'},
        'Dr. Sanay Naha': {'Link': 'C-533'},
        'Garima Jain': {'Link': 'C-534'},
        'Dr. Ashok Patel': {'Link': 'C-535'},
        'Satyam Ravi': {'Link': 'C-536'},
        'Udai Kumar': {'Link': 'C-537'},
        'Shilpa Suman': {'Link': 'C-538'},
        'Pratosh Kumar Pal': {'Link': 'C-539'},
        'Prasad Begde': {'Link': 'C-540'},
        'Dr. Abha Gupta': { 'Link': 'AB-306' },
        'Dr. Sonal Trivedi': { 'Link': 'AB-306' },
        'Mr. RAVI KUMAR SINGH': { 'Link': 'AB-310' },
        'Priyanka Mishra': { 'Link': 'AB-406' },
        'Dr. S. VAIRACHILAI': { 'Link': 'AB-406' },
        'Dr. Kamlesh Chandravanshi': { 'Link': 'AB-410' },
        'P. Narendra Babu': { 'Link': 'AB-410' },
        'Mr. Vikas Kumar Jain': { 'Link': 'AB-506' },
        'Mr. Narendra Kumar': { 'Link': 'AB-506' },
        'Dr. Anil Kumar Yadav': { 'Link': 'AB-510' },
        'M.R. Thiyagu Priyadharsan': { 'Link': 'AB-510' },
        'Dr. Vipin Mishra': { 'Link': 'AB-210' },
        'Dr. Subrata Nath': { 'Link': 'AB-210' },
        'Rakesh Shrivastava': {'Link': 'AB-210'}       
        
};

var originalDropdownOptions3 = Array.from(document.getElementById("dropdowncabin").options);

function filterDropdowncabin() {
    var cabininput = document.getElementById("cabininput").value.toLowerCase();
    var dropdowncabin = document.getElementById("dropdowncabin");

    dropdowncabin.innerHTML = "";

    var filteredOptions1 = originalDropdownOptions3.filter(function (option) {
        return option.text.toLowerCase().includes(cabininput);
    });

    for (var i = 0; i < filteredOptions1.length; i++) {
        dropdowncabin.appendChild(filteredOptions1[i]);
    }
}

document.getElementById("submitcabin").addEventListener('click', function () {
    let dropdownc = document.getElementById("dropdowncabin");
    let selectedcabin = dropdownc.value;

    if (selectedcabin in cabins) {
        let cabin = document.getElementById("cabin");
;

    } else {
        let cabin = document.getElementById("cabin");
        cabin.innerHTML = `Please Select a Course from the available options`;
        cabin.setAttribute("style", `color: #FF1800;`);
    }
});




document.getElementById("submitcabin").addEventListener('click', function () {
    let dropdownc = document.getElementById("dropdowncabin");
    let selectedcabin = dropdownc.value;

    if (selectedcabin in cabins) {
        let cabin = document.getElementById("cabin");
        let Link = cabins[selectedcabin]['Link'];
        cabin.innerHTML = `${Link}`;
    } else {
        let cabin = document.getElementById("cabin");
        cabin.innerHTML = `Please Select a Course from the available options`;
    }
});
